### PR TITLE
[v0.5.1] toJSON serialises the instance

### PR DESCRIPTION
**Pull request by caccialdo**
# Changes
* stringifiing the instance no longer turns it into a decimal as a string (prefer `.toString()` method for that purpose). Avoids loosing the currency.
* Removes some trailing spaces in the edited files (consequence of the `.editorconfig` file from previous #7).

### CODE REVIEW

**Comment by drewclauson** [comment]
+1

**Comment by caccialdo** [comment]
@davidkalosi Any comment on this change?

**Comment by davidkalosi** [comment]
sorry for the delay I am quite overloaded these days. Will look into this ASAP.

**Comment by davidkalosi** [comment]
merged. thanks !!!

**Pull request merged**
