### PR TITLE
fromDecimal with rounder

### PR DESCRIPTION
**Pull request by alexander-hq**
Same as fromDecimal but it will work with any number of decimal digits.

### CODE REVIEW

**Comment by davidkalosi** [comment]
Hi, 

I would suggest a slightly different implementation - refactor the fromDecimal method that it takes an optional 3rd argument which is the rounding fucntion or falls back to the default behaviour if not supplied. I think this will result in a cleaner API than adding one additional method. what do you think ?

**Comment by alexander-hq** [comment]
Okay

**Comment by davidkalosi** [comment]
merged. thank you for contribution

**Comment by alexander-hq** [comment]
@davidkalosi Thanks. When it will be available on npmjs.com?

**Comment by davidkalosi** [comment]
published today, version 0.6.2

**Pull request merged**
