### PR TITLE
fix rounder 0.1 issue

### PR DESCRIPTION
**Pull request by dnfrolov**

### CODE REVIEW

**Comment by davidkalosi** [comment]
looking at the code, wouldn't it make sense to initialize the default rounder (Math.round) in case none was supplied? That would remove the else branch.

**Comment by dnfrolov** [comment]
@davidkalosi 
else branch makes code more explicit and gives an opportunity to explain why we do this round operation

**Comment by jamiesoncj** [comment]
I would just like to add a voice in support of this PR - I got tripped up by this package with similar issues to #10 and #28.

My suggestion would be to always have a default rounder in place, otherwise it's easy to run into unexpected situations e.g. `Money.fromDecimal(157.27, "GBP");` throws an error.

Therefore I support merging this PR, and I agree with @dnfrolov that the explicit else branch is nice and readable.

**Comment by tastypackets** [comment]
No need to add another if statement since earlier in code there is already a check for undefined. Review the commit I added to my branch, I feel this may be a cleaner way to handle it.

https://github.com/tastypackets/js-money/commit/0151c0bb3a051b448deeae765354f6795efd4b2f

**Comment by davidkalosi** [comment]
@tastypackets can you do a PR I like your solution more. I will then reject this PR and merge yours.
thanks

**Comment by davidkalosi** [comment]
Closing in favor of PR #34

**Pull request closed without merging**
